# Main screen workspaces
workspace=1,monitor:desc:LG Electronics LG ULTRAGEAR 0x00095E49,default:true
workspace=2,monitor:desc:LG Electronics LG ULTRAGEAR 0x00095E49
workspace=3,monitor:desc:LG Electronics LG ULTRAGEAR 0x00095E49
workspace=4,monitor:desc:LG Electronics LG ULTRAGEAR 0x00095E49
workspace=5,monitor:desc:LG Electronics LG ULTRAGEAR 0x00095E49

# Left screen
workspace=6,monitor:desc:LG Electronics LG ULTRAGEAR 206MAEG84N00,default:true
workspace=7,monitor:desc:LG Electronics LG ULTRAGEAR 206MAEG84N00
workspace=8,monitor:desc:LG Electronics LG ULTRAGEAR 206MAEG84N00
workspace=9,monitor:desc:LG Electronics LG ULTRAGEAR 206MAEG84N00
workspace=10,monitor:desc:LG Electronics LG ULTRAGEAR 206MAEG84N00

# Right (laptop)
workspace=11,monitor:desc:BOE 0x0CB7,default:true
workspace=12,monitor:desc:BOE 0x0CB7
workspace=13,monitor:desc:BOE 0x0CB7
workspace=14,monitor:desc:BOE 0x0CB7
workspace=15,monitor:desc:BOE 0x0CB7
